#include "data.h"

/* ---------- NORMAL MODE: MOVEMENT ---------- */
static const VimEntry tab_move[] = {
    {"h j k l",     "Move left / down / up / right"},
    {"w",           "Jump to start of next word"},
    {"W",           "Jump to next WORD (whitespace separated)"},
    {"b",           "Jump to start of previous word"},
    {"B",           "Jump to previous WORD"},
    {"e",           "Jump to end of word"},
    {"E",           "Jump to end of WORD"},
    {"ge",          "Jump to end of previous word"},
    {"0",           "Jump to start of line (column 0)"},
    {"^",           "Jump to first non-blank character of line"},
    {"$",           "Jump to end of line"},
    {"g_",          "Jump to last non-blank character of line"},
    {"gg",          "Go to first line of file"},
    {"G",           "Go to last line of file"},
    {"NG / :N",     "Go to line N"},
    {"H",           "Move to top of screen"},
    {"M",           "Move to middle of screen"},
    {"L",           "Move to bottom of screen"},
    {"%",           "Jump to matching bracket ( ) { } [ ]"},
    {"Ctrl-f",      "Page forward (down)"},
    {"Ctrl-b",      "Page backward (up)"},
    {"Ctrl-d",      "Scroll down half a page"},
    {"Ctrl-u",      "Scroll up half a page"},
    {"Ctrl-e",      "Scroll down one line (keep cursor)"},
    {"Ctrl-y",      "Scroll up one line (keep cursor)"},
    {"zz",          "Center current line on screen"},
    {"zt / zb",     "Scroll current line to top / bottom"},
    {"f{char}",     "Jump to next occurrence of char in line"},
    {"F{char}",     "Jump to previous occurrence of char in line"},
    {"t{char}",     "Jump to just before next occurrence of char"},
    {"T{char}",     "Jump to just after previous occurrence of char"},
    {";",           "Repeat last f/F/t/T"},
    {",",           "Repeat last f/F/t/T reversed"},
    {"( )",         "Jump to previous / next sentence"},
    {"{ }",         "Jump to previous / next paragraph"},
    {"''",          "Jump back to previous cursor position"},
    {"`.",          "Jump to position of last edit"},
    {"Ctrl-o",      "Jump to older position in jump list"},
    {"Ctrl-i",      "Jump to newer position in jump list"},
};

/* ---------- NORMAL MODE: EDITING ---------- */
static const VimEntry tab_edit[] = {
    {"i",           "Insert before cursor"},
    {"I",           "Insert at start of line"},
    {"a",           "Append after cursor"},
    {"A",           "Append at end of line"},
    {"o",           "Open new line below and insert"},
    {"O",           "Open new line above and insert"},
    {"x",           "Delete character under cursor"},
    {"X",           "Delete character before cursor"},
    {"r{char}",     "Replace single character under cursor"},
    {"R",           "Enter Replace mode"},
    {"s",           "Delete character and insert (substitute)"},
    {"S",           "Delete line and insert (substitute line)"},
    {"cc",          "Change (replace) entire line"},
    {"cw",          "Change to end of word"},
    {"c$ / C",      "Change to end of line"},
    {"dd",          "Delete (cut) current line"},
    {"D",           "Delete to end of line"},
    {"dw",          "Delete to start of next word"},
    {"d0",          "Delete to start of line"},
    {"d$",          "Delete to end of line"},
    {"J",           "Join current line with next line"},
    {"gJ",          "Join lines without inserting a space"},
    {"~",           "Toggle case of character under cursor"},
    {"g~~ / g~~",   "Toggle case of current line"},
    {"gu{motion}",  "Lowercase text covered by motion"},
    {"gU{motion}",  "Uppercase text covered by motion"},
    {"u",           "Undo last change"},
    {"Ctrl-r",      "Redo last undone change"},
    {".",           "Repeat last change"},
    {">>",          "Indent line one shiftwidth"},
    {"<<",          "Un-indent line one shiftwidth"},
    {"=={motion}",  "Auto-indent lines"},
};

/* ---------- NORMAL MODE: COPY / PASTE (registers) ---------- */
static const VimEntry tab_yank[] = {
    {"yy / Y",      "Yank (copy) current line"},
    {"yw",          "Yank to start of next word"},
    {"y$",          "Yank to end of line"},
    {"y0",          "Yank to start of line"},
    {"yG",          "Yank to end of file"},
    {"p",           "Paste after cursor / below line"},
    {"P",           "Paste before cursor / above line"},
    {"gp",          "Paste after cursor, leave cursor after text"},
    {"gP",          "Paste before cursor, leave cursor after text"},
    {"\"ayy",       "Yank line into register a"},
    {"\"ap",        "Paste from register a"},
    {"\"+y",        "Yank into system clipboard register"},
    {"\"+p",        "Paste from system clipboard register"},
    {"\"_d",        "Delete into black-hole register (no yank)"},
    {":reg",        "List contents of all registers"},
    {"qa ... q",    "Record a macro into register a"},
    {"@a",          "Play back macro in register a"},
    {"@@",          "Repeat last played macro"},
};

/* ---------- NORMAL MODE: SEARCH & REPLACE ---------- */
static const VimEntry tab_search[] = {
    {"/pattern",         "Search forward for pattern"},
    {"?pattern",         "Search backward for pattern"},
    {"n",                "Repeat search in same direction"},
    {"N",                "Repeat search in opposite direction"},
    {"*",                "Search forward for word under cursor"},
    {"#",                "Search backward for word under cursor"},
    {":noh",             "Clear search highlighting"},
    {":%s/old/new/g",    "Replace all 'old' with 'new' in file"},
    {":%s/old/new/gc",   "Replace all, confirm each substitution"},
    {":s/old/new/",      "Replace first match on current line"},
    {":s/old/new/g",     "Replace all matches on current line"},
    {":10,20s/old/new/g","Replace on line range 10 to 20"},
    {":g/pattern/d",     "Delete all lines matching pattern"},
    {":g/pattern/normal @a", "Run macro a on every matching line"},
};

/* ---------- INSERT MODE ---------- */
static const VimEntry tab_insert[] = {
    {"Esc / Ctrl-[", "Leave Insert mode, return to Normal mode"},
    {"Ctrl-c",       "Leave Insert mode (skips abbreviation expansion)"},
    {"Ctrl-w",       "Delete word before cursor"},
    {"Ctrl-u",       "Delete to start of line"},
    {"Ctrl-h",       "Delete character before cursor (backspace)"},
    {"Ctrl-t",       "Indent current line"},
    {"Ctrl-d",       "Un-indent current line"},
    {"Ctrl-n",       "Autocomplete: next match"},
    {"Ctrl-p",       "Autocomplete: previous match"},
    {"Ctrl-r {reg}", "Insert contents of a register"},
    {"Ctrl-v {code}","Insert a literal / special character"},
    {"Ctrl-o {cmd}", "Run one Normal-mode command, then return to Insert"},
    {"Ctrl-a",       "Insert previously inserted text again"},
};

/* ---------- VISUAL MODE ---------- */
static const VimEntry tab_visual[] = {
    {"v",            "Start character-wise Visual mode"},
    {"V",            "Start line-wise Visual mode"},
    {"Ctrl-v",       "Start block-wise Visual mode"},
    {"o",            "Move to other end of selection"},
    {"gv",           "Reselect last visual selection"},
    {"aw / aW",      "Select a word / WORD (text object)"},
    {"iw / iW",      "Select inner word / WORD (text object)"},
    {"ap / ip",      "Select a paragraph / inner paragraph"},
    {"ib / ab",      "Select inner / a block ( ) pair"},
    {"iB / aB",      "Select inner / a block { } pair"},
    {"it / at",      "Select inner / a tag block <tag>...</tag>"},
    {"d",            "Delete selection"},
    {"y",            "Yank selection"},
    {"c",            "Change selection"},
    {"> / <",        "Indent / un-indent selection"},
    {"U / u",        "Uppercase / lowercase selection"},
    {"J",            "Join selected lines"},
    {"= ",           "Auto-indent selection"},
    {":",            "Enter Ex command restricted to selection ('<,'>)"},
    {"I (block mode)","Insert text at start of every selected line"},
    {"A (block mode)","Append text at end of every selected line"},
};

/* ---------- COMMAND-LINE (EX) MODE ---------- */
static const VimEntry tab_cmdline[] = {
    {":w",              "Write (save) the file"},
    {":w filename",     "Save a copy as filename"},
    {":q",              "Quit (fails if unsaved changes)"},
    {":q!",             "Quit and discard changes"},
    {":wq / :x / ZZ",   "Save and quit"},
    {":wqa",            "Save and quit all open windows"},
    {":e filename",     "Open (edit) a file"},
    {":e!",             "Reload file, discarding changes"},
    {":r filename",     "Insert contents of a file below cursor"},
    {":r !cmd",         "Insert output of a shell command"},
    {":!cmd",           "Run an external shell command"},
    {":set number",     "Show line numbers"},
    {":set nu! ",       "Toggle line numbers"},
    {":set ic",         "Ignore case in searches"},
    {":syntax on",      "Enable syntax highlighting"},
    {":history",        "Show command-line history"},
    {":help topic",     "Open help for a topic"},
};

/* ---------- REPLACE MODE ---------- */
static const VimEntry tab_replace[] = {
    {"R",            "Enter Replace mode from Normal mode"},
    {"(typing)",     "Overwrite characters as you type"},
    {"Backspace",    "Restore the original overwritten character"},
    {"Esc",          "Leave Replace mode, return to Normal mode"},
    {"gR",           "Enter Virtual Replace mode (respects tabs/width)"},
    {"r{char}",      "Replace exactly one character (Normal mode)"},
    {"NrX",          "Replace next N characters with X"},
};

/* ---------- WINDOWS, TABS & BUFFERS ---------- */
static const VimEntry tab_windows[] = {
    {":split / :sp",      "Split window horizontally"},
    {":vsplit / :vsp",    "Split window vertically"},
    {"Ctrl-w s / v",      "Split window horizontally / vertically"},
    {"Ctrl-w w",          "Cycle to next window"},
    {"Ctrl-w h/j/k/l",    "Move to window left/down/up/right"},
    {"Ctrl-w q",          "Close current window"},
    {"Ctrl-w =",          "Make all windows equal size"},
    {":tabnew",           "Open a new tab"},
    {"gt / gT",           "Go to next / previous tab"},
    {":tabclose",         "Close current tab"},
    {":ls / :buffers",    "List open buffers"},
    {":bnext / :bn",      "Switch to next buffer"},
    {":bprev / :bp",      "Switch to previous buffer"},
    {":b N",              "Switch to buffer number N"},
    {":bd",               "Delete (close) current buffer"},
};

/* ---------- MACROS & MISC ---------- */
static const VimEntry tab_misc[] = {
    {"qa {keys} q",    "Record keystrokes into macro register a"},
    {"@a",             "Execute macro register a"},
    {"5@a",            "Execute macro a five times"},
    {"@:",             "Repeat last Ex command"},
    {"Ctrl-a",         "Increment number under cursor"},
    {"Ctrl-x",         "Decrement number under cursor"},
    {"m{letter}",      "Set a mark at cursor position"},
    {"'{letter}",      "Jump to line of mark"},
    {"`{letter}",      "Jump to exact position of mark"},
    {"zf{motion}",     "Create a fold over motion"},
    {"za",             "Toggle (open/close) fold under cursor"},
    {"zR / zM",        "Open all folds / close all folds"},
    {"Ctrl-g",         "Show file name and cursor position"},
    {"g Ctrl-g",       "Show cursor position, word/char counts"},
};

const VimTab g_tabs[] = {
    { "MOVEMENT",   "Normal mode: navigating the buffer",       tab_move,    (int)(sizeof(tab_move)/sizeof(tab_move[0]))       },
    { "EDITING",    "Normal mode: inserting, changing, deleting", tab_edit,  (int)(sizeof(tab_edit)/sizeof(tab_edit[0]))       },
    { "YANK/PASTE", "Normal mode: registers, copy & paste",     tab_yank,    (int)(sizeof(tab_yank)/sizeof(tab_yank[0]))       },
    { "SEARCH",     "Normal mode: search & substitute",         tab_search,  (int)(sizeof(tab_search)/sizeof(tab_search[0]))   },
    { "INSERT",     "Insert mode: keys while typing text",      tab_insert,  (int)(sizeof(tab_insert)/sizeof(tab_insert[0]))   },
    { "VISUAL",     "Visual / Visual-line / Visual-block mode", tab_visual,  (int)(sizeof(tab_visual)/sizeof(tab_visual[0]))   },
    { "CMDLINE",    "Command-line (Ex) mode, after ':'",        tab_cmdline, (int)(sizeof(tab_cmdline)/sizeof(tab_cmdline[0])) },
    { "REPLACE",    "Replace / Virtual Replace mode",           tab_replace, (int)(sizeof(tab_replace)/sizeof(tab_replace[0])) },
    { "WINDOWS",    "Windows, tabs & buffers",                  tab_windows, (int)(sizeof(tab_windows)/sizeof(tab_windows[0])) },
    { "MACROS",     "Macros & miscellaneous commands",          tab_misc,    (int)(sizeof(tab_misc)/sizeof(tab_misc[0]))       },
};

const int g_tab_count = (int)(sizeof(g_tabs)/sizeof(g_tabs[0]));
